### PR TITLE
Fix modelsim regex

### PR DESCRIPTION
**Pull request by go2sh**
Somehow the regex does not work any more. Removing the newline char fixes the problem.

### CODE REVIEW

**Comment by deprint** [comment]
I wonder why though, the specs still seem to work (that failure in Travis CI is caused by something else).

**Comment by go2sh** [comment]
I have no idea. I just recognized that after some update then profile wasn't showing up any more under windows. I don't now weather this is related?

**Comment by deprint** [comment]
Did errors not get highlighted or did the profile not show up in the settings page?
I'm wondering how this `$` could have caused a problem. Other profiles use it as well and they work fine.

**Comment by go2sh** [comment]
Just no highlighting including file detection, line detection, error detection and message.

**Comment by deprint** [comment]
Well I don't understand why (yet), but the `$` is a bit redundant anyway 😄 
Thanks for the contribution.

**Comment by go2sh** [comment]
Awesome work. Keep it up. I have create some more profiles and use build-tools every day. :-)

**Pull request merged**
